travis:
  secure:
    BINSTAR_TOKEN: CHeMpJtPyZyo1VeFpCp/W3QVrrQbOgK8zon/i7OIVCvlrISmDj6g7eF6RDzS6O0A29PiXupLD5XOulMbkFPwmr1iun3hi/OEQQRosd5iQ6jOSz8ljeGYfxhqChiOcunNkZixzr4ZPSt8pneBEp1yilBEcfnZcKewUnFRITLa+i0CZ9LKnIZa3dU7VDn/8tDAjB/j+j+DKZW1K0PupwP1e1qcc0hBgmLqKTD553WcPiEDUIc3z6XMvhoKKqS084dKCAwvvbCgYygtxq/xt+iiowQkTG9oxgRp4AucrglO3R+9d7jLC5u0ARDSXBoJSobUItTHkFDEPSJX5qFS6/MMb1hW8GpSYtrAR5aNO3AvZbPOE1HnZ2eQ0SJLmle+U9Gy2xN6XG4O5cOlcwNuDc7FLq1RaN/NN7idOW59/ojc0I/CdBZr48hbjY/SFIY2HMkHrANtsrAovocpoxCJdn627B+4Qaq6s0xgL+ANG0xpjKG8ykuiMEvQFaXCqRiWjHwd5zAMYbhQi0iETT9QpvQYBlEcJ8TwEh77cTtdyLtEJ2pS4q5+BvPhbosWHkMaDB0HsF998HqX/B859UJ1tD89L0ju571t2FpQe7OClWi32eqiNLiiZytRjzKiXrDxi6H6q/YIMCg3qULIygGQHex/sZby31kzCa1OqdmkbqzLj9k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
